version: '3'
services:
  freecaster:
    build: 
      dockerfile: Dockerfile
      context: ./
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      FREESTUFF_WEBHOOK_SECRET: "wdaji29dJadj91jAjd9a92eDak2"
      LOG_LEVEL: "debug"